version: '3'

networks:
  qrt_qm_services:
    driver: bridge

services:

  qrt_qm_www:
    image: qrt_question_manager:1.0.0
    container_name: qrt_qm_www
    build: ./
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      restart_policy:
        condition: any
    environment:
      PORT: 3000
      AMQP_URL: 'amqp://qrt_rabbitmq'
    ports:
      - "3000:3000"
    networks:
      - qrt_qm_services

  qrt_qm_qgen:
    image: qrt_question_manager:1.0.0
    container_name: qrt_qm_qgen
    build: ./
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      restart_policy:
        condition: any
    environment:
      AMQP_URL: 'amqp://qrt_rabbitmq'
    entrypoint:
      - "npm run qgen"
    networks:
      - qrt_qm_services

  qrt_rabbitmq:
    image: rabbitmq:management
    container_name: qrt_rabbitmq
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      restart_policy:
        condition: any
    expose:
      - 5672
      - 15672
    ports:
      - "15672:15672"